# Generated by Django 5.1.1 on 2024-09-16 10:59

from django.db import migrations, models #type: ignore


class Migration(migrations.Migration):

    initial = True

    dependencies: list = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Done', 'Done'), ('Not Done', 'Not Done'), ('In Progress', 'In Progress')], default='not_done', max_length=20)),
            ],
        ),
    ]
